# Common hyperparameters to both TQC and SAC
common:
  policy: "MlpPolicy"
  learning_rate: !!float 3e-4
  gamma: 0.99
  tau: 0.005
  buffer_size: 1000000

# Algorithm dependent hyperparameters
tqc:
  policy_kwargs:
    n_critics: 5
    n_quantiles: 25
    net_arch:
      pi: [256, 256]
      qf: [512, 512, 512]

sac:
  policy_kwargs:
    n_critics: 2
    net_arch:
      pi: [256, 256]
      qf: [256, 256]

# Environment dependent hyperparameters
Hopper-v3:
  top_quantiles_to_drop_per_net: 5

HalfCheetah-v3:
  top_quantiles_to_drop_per_net: 0

Walker2d-v3:
  top_quantiles_to_drop_per_net: 2

Ant-v3:
  top_quantiles_to_drop_per_net: 2

Humanoid-v3:
  top_quantiles_to_drop_per_net: 2